### ISSUE TITLE
Design a Logo

### ISSUE THREAD

**Issue by toth2000** [toth2000/chatBit#21]
Design a Logo for the App and:
- Update the Favicon
- InfoBar Component (Logo Img)

**Comment by linzof** [comment]
how do you like this? If you dig it - I'll go ahead and take care of issue #21.
![image](https://user-images.githubusercontent.com/86526405/126879362-876bfcb8-4c13-4dce-ab76-01f8f1977c23.png)

**Comment by toth2000** [comment]
@linzof This looks awesome. Very nice work Chris!!

**Comment by linzof** [comment]
Sweet. I'll take care of issue #21 in the morning.

**Comment by linzof** [comment]
Hey there,

After attempting to fix this issue, there seems to be other issues on the app. 
On vs code open, I immediately noticed that on the index.js>Line 3  "import App from './app';" was incorrect - I fixed this issue to compile the app. 

After that, the app isn't loading in the browser and seems to be crashing all of my browser extensions. 
I checked the console and saw an error: [HMR] Waiting for update signal from WDS...
So I fixed this, but I am still not able to see anything on the web. Would you know what is going on?

**Comment by toth2000** [comment]
> Hey there,
> 
> After attempting to fix this issue, there seems to be other issues on the app.
> On vs code open, I immediately noticed that on the index.js>Line 3 "import App from './app';" was incorrect - I fixed this issue to compile the app.
> 
> After that, the app isn't loading in the browser and seems to be crashing all of my browser extensions.
> I checked the console and saw an error: [HMR] Waiting for update signal from WDS...
> So I fixed this, but I am still not able to see anything on the web. Would you know what is going on?

Rename app.js file to App.js 
Since you are now using ``` import App from './App' ``` . If this doesn't fix this issue, then please share the error message screenshot and I will look into it.

**Comment by linzof** [comment]
was able to get through. 
pull request for issue 21 has been submitted

**Comment by toth2000** [comment]
Fixed with #22
