### ISSUE TITLE
Add close button image to InfoBar

### ISSUE THREAD

**Issue by toth2000** [toth2000/chatBit#23]
**Describe the bug**
The info bar is missing a close button image, add the image and fix the bug.

Add image to file:
src/components/InfoBar/InfoBar.jsx

if CSS modification is required then add CSS to file
src/components/InfoBar/InfoBar.css

**To Reproduce**
1. Go to repo URL
2. Join a room
3. See at Top close button image is missing

**Expected behavior**
Should display an image with cross

**Comment by malburo** [comment]
close button has on infobar, you can be description that more?

**Comment by toth2000** [comment]
@malburo sorry, this issue has been fixed.
