### ISSUE TITLE
Change Page Title

### ISSUE THREAD

**Issue by toth2000** [toth2000/chatBit#24]
Describe the bug
Currently, the Page Title is React App (the default). Change it our project name, i.e `ChatBit`

Steps to fix the issue:

1. Open `public/index.html`
2. Change ` <title>React App</title>` to ` <title>ChatBit</title>`

**Comment by AbhishekSharma-86** [comment]
Hey! plz assign me this issue, I would love to work on this since i am a beginner to open source

**Comment by toth2000** [comment]
@AbhishekSharma-86 sure. If you face any issue feel free to ping me in the comments.
