### ISSUE TITLE
Create CSS for Chat Component

### ISSUE THREAD

**Issue by toth2000** [toth2000/chatBit#5]
**Describe the solution you'd like**
Create CSS for Chat Component.
Src/components/Chat/Chat.css

The Chat component contains three other components i.e InfoBar, Messages, and Input Component.
The Chat.css should apply to the Chat Component only. It can deal with the positioning of child components as each other component have their own CSS.

**Comment by alvarotorrestx** [comment]
Hi, can I be assigned this to work on please?

**Comment by toth2000** [comment]
Thanks for your interest in contributing to this project. Yeah sure! Assigned.

**Comment by alvarotorrestx** [comment]
Hi just to ensure, this is only styling for positioning, widths, etc. correct? Nothing as per styles dealing with color, bg color, etc?
Just want to double check before I submit any PR @toth2000

**Comment by alvarotorrestx** [comment]
> Hi just to ensure, this is only styling for positioning, widths, etc. correct? Nothing as per styles dealing with color, bg color, etc?
> Just want to double check before I submit any PR @toth2000

Mainly questioning since each other component does or will have their own css

**Comment by toth2000** [comment]
@alvarotorrestx  Yes, you are correct.

**Comment by toth2000** [comment]
Closed with PR #9
