### ISSUE TITLE
Create CSS for Input Component

### ISSUE THREAD

**Issue by toth2000** [toth2000/chatBit#6]
### Src/components/Input/Input.css

The Input component has an input field that takes the message text as input and a button for sending the message.
The Input.css should apply to this component only.

**Comment by alvarotorrestx** [comment]
Hi, can I be assigned this to work on please?

**Comment by toth2000** [comment]
@alvarotorrestx Thanks for your interest in contributing to this project.

**Comment by toth2000** [comment]
Solved with PR #9
